services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      dev_db:
        condition: service_healthy
    restart: unless-stopped

  dev_db:
    image: postgres:13
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASS}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - "${DEV_DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_DB_USER} -d ${DEV_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  test_db:
    image: postgres:13
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_dev_data:

