# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\x12\tapp.proto\"s\n\rScheduleModel\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08medicine\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x05\x12\x1a\n\rduration_days\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x10\n\x0e_duration_days\" \n\rUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"5\n\rScheduleQuery\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bschedule_id\x18\x02 \x01(\x05\"&\n\x0fScheduleIdModel\x12\x13\n\x0bschedule_id\x18\x01 \x01(\x05\"4\n\x15SchedulesListResponse\x12\x1b\n\x13\x61\x63tive_schedule_ids\x18\x01 \x03(\x05\"P\n\x14\x46ullScheduleResponse\x12\x13\n\x0bschedule_id\x18\x01 \x01(\x05\x12\x10\n\x08medicine\x18\x02 \x01(\t\x12\x11\n\ttime_list\x18\x03 \x03(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\rErrorResponse\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\t\"\x85\x01\n\x10ScheduleResponse\x12\x38\n\rfull_schedule\x18\x01 \x01(\x0b\x32\x1f.app.proto.FullScheduleResponseH\x00\x12-\n\x07message\x18\x02 \x01(\x0b\x32\x1a.app.proto.MessageResponseH\x00\x42\x08\n\x06result\"\xb5\x01\n\x18\x44ynamicSchedulesResponse\x12N\n\x0eschedule_times\x18\x01 \x03(\x0b\x32\x36.app.proto.DynamicSchedulesResponse.ScheduleTimesEntry\x1aI\n\x12ScheduleTimesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.app.proto.TimeList:\x02\x38\x01\"\x19\n\x08TimeList\x12\r\n\x05times\x18\x01 \x03(\t2\xbd\x02\n\x0fScheduleService\x12\x43\n\x0b\x41\x64\x64Schedule\x12\x18.app.proto.ScheduleModel\x1a\x1a.app.proto.ScheduleIdModel\x12J\n\x0cGetSchedules\x12\x18.app.proto.UserIdRequest\x1a .app.proto.SchedulesListResponse\x12H\n\x0fGetScheduleById\x12\x18.app.proto.ScheduleQuery\x1a\x1b.app.proto.ScheduleResponse\x12O\n\x0eGetNextTakings\x12\x18.app.proto.UserIdRequest\x1a#.app.proto.DynamicSchedulesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNAMICSCHEDULESRESPONSE_SCHEDULETIMESENTRY']._loaded_options = None
  _globals['_DYNAMICSCHEDULESRESPONSE_SCHEDULETIMESENTRY']._serialized_options = b'8\001'
  _globals['_SCHEDULEMODEL']._serialized_start=29
  _globals['_SCHEDULEMODEL']._serialized_end=144
  _globals['_USERIDREQUEST']._serialized_start=146
  _globals['_USERIDREQUEST']._serialized_end=178
  _globals['_SCHEDULEQUERY']._serialized_start=180
  _globals['_SCHEDULEQUERY']._serialized_end=233
  _globals['_SCHEDULEIDMODEL']._serialized_start=235
  _globals['_SCHEDULEIDMODEL']._serialized_end=273
  _globals['_SCHEDULESLISTRESPONSE']._serialized_start=275
  _globals['_SCHEDULESLISTRESPONSE']._serialized_end=327
  _globals['_FULLSCHEDULERESPONSE']._serialized_start=329
  _globals['_FULLSCHEDULERESPONSE']._serialized_end=409
  _globals['_MESSAGERESPONSE']._serialized_start=411
  _globals['_MESSAGERESPONSE']._serialized_end=445
  _globals['_ERRORRESPONSE']._serialized_start=447
  _globals['_ERRORRESPONSE']._serialized_end=478
  _globals['_SCHEDULERESPONSE']._serialized_start=481
  _globals['_SCHEDULERESPONSE']._serialized_end=614
  _globals['_DYNAMICSCHEDULESRESPONSE']._serialized_start=617
  _globals['_DYNAMICSCHEDULESRESPONSE']._serialized_end=798
  _globals['_DYNAMICSCHEDULESRESPONSE_SCHEDULETIMESENTRY']._serialized_start=725
  _globals['_DYNAMICSCHEDULESRESPONSE_SCHEDULETIMESENTRY']._serialized_end=798
  _globals['_TIMELIST']._serialized_start=800
  _globals['_TIMELIST']._serialized_end=825
  _globals['_SCHEDULESERVICE']._serialized_start=828
  _globals['_SCHEDULESERVICE']._serialized_end=1145
# @@protoc_insertion_point(module_scope)
